class Config:
    BURST_GAP_THRESHOLD = 30
    MIN_BURST_CHARS = 2
    TOOLTIP_MAX_LINES = 30
    TOOLTIP_WIDTH = 60
    HOVER_DISTANCE_THRESHOLD = 15
    CLICK_DISTANCE_THRESHOLD = 0.05
    SESSION_PADDING_SECONDS = 120

    CROSSHAIR_KEY = ' '

    CHART_FIGURE_SIZE = (16, 12)
    CHART_FIGURE_SIZE_NO_STUDENTS = (16, 10)

    BAR_COLOR = '#777777'
    BAR_EDGE_COLOR = '#000000'
    BAR_ALPHA = 0.7
    BAR_MIN_WIDTH_SECONDS = 8

    SESSION_RATE_COLOR = '#888888'
    ACTIVE_RATE_COLOR = 'black'
    LINE_ALPHA = 0.7
    LINE_WIDTH = 2

    CUMULATIVE_LINE_COLOR = '#CCCCCC'
    CUMULATIVE_LINE_WIDTH = 2
    CUMULATIVE_FILL_ALPHA = 0.3

    BURST_MARKER_COLOR = 'black'
    BURST_MARKER_ALPHA = 0.5
    BURST_MARKER_SIZE = 25

    DEV_DOT_COLOR = '#22aa22'
    DEV_DOT_EDGE_COLOR = '#116611'
    ANCHOR_DOT_COLOR = '#007acc'
    ANCHOR_DOT_EDGE_COLOR = '#005a99'
    MOVE_DOT_COLOR = '#e07020'
    MOVE_DOT_EDGE_COLOR = '#a04010'

    QUESTION_ANSWERED_COLOR = 'blue'
    QUESTION_UNANSWERED_COLOR = '#EF9A9A'
    QUESTION_STUDENT_COLOR = 'orange'
    QUESTION_HELP_COLOR = '#66BB6A'
    QUESTION_ALPHA = 0.3
    QUESTION_LINE_WIDTH = 3
    QUESTION_LINE_ALPHA = 0.6

    STUDENT_ANSWERED_COLOR = '#1565C0'
    STUDENT_ASKED_COLOR = '#F9A825'
    STUDENT_HELPED_COLOR = '#66BB6A'
    STUDENT_NO_ANSWER_COLOR = '#CCCCCC'
    STUDENT_MARKER_SIZE = 60
    STUDENT_MARKER_SIZE_ANSWERED = 144
    STUDENT_STAR_HALO1_SIZE = 300
    STUDENT_STAR_HALO2_SIZE = 520
    STUDENT_ALPHA = 0.6
    STUDENT_ALPHA_ANSWERED = 1.0
    STUDENT_EDGE_WIDTH = 2

    SHOW_ALL_FOLLOW_DOTS = True

    DOT_JITTER_X_SECONDS = 30
    DOT_JITTER_Y_PCT     = 2.5
